### ISSUE TITLE
Support label missing when two children of a node have zero length

### ISSUE THREAD

**Issue by terrycojones** [iqtree/iqtree2#343] opened 2024-11-01 12:01 UTC
Last night I was examining the output of `iqtree2 -bb` (version 2.3.6 on OS X 14.5) and noticed that there were many nodes that had no (support) label.

For example, I have an internal node (`A`) that has a label on it (say 70) and one of its children (`B`) has no label. `B` has two other edges (leading to tip nodes in this case, but not always) and both those children have zero length edges. Given that `A` has support of 70, I would expect a label on `B`.

In ASCII art, the situation looks like this:

```
               |
               |  length=0.003  label=70
               |
               |
               * A
              /|
             / |  length=0.001 (but no label)
            /  |
           /   |
          /    |
         *     * B
              / \
             /   \
        0.0 /     \ 0.0 (zero length to both children of B)
           /       \
          /         \
        Tip         Tip
```

I see this pattern 25 times in my tree with 248 internal nodes, and it's always the case that two of the edges leaving the node with no label (`B` in the above example) have lengths of zero. For that reason it feels like there might be a bug due to an `if` condition somewhere in the bootstrap support annotation that causes the node not to be given a support label.

I'm posting here ahead of trying to debug this, in the hope that either I'm misunderstanding something or that it's easy for someone familiar with the code base to spot where this is happening. Thanks!

**Comment by roblanf** [comment] 2024-11-03 01:22
@terrycojones, I'm not sure of the answer to your actual question of why this occurs. But I wonder if it's because by default IQ-TREE removes identical sequences and adds them back in at the end. 

One thing you could try is use the `-keep-ident` flag, and see if that makes a difference. This forces IQ-TREE to keep all identical sequences throughout. Slightly slower (or a lot slower, if you have vast numbers of identical sequences) but perhaps fixes the issue?

**Comment by terrycojones** [comment] 2024-11-03 10:23
Hi @roblanf - thanks for the reply. You're right, the issue goes away when I add `-keep-ident`. I also checked the count of 'is ignored but added at the end' messages in the log of my original run, and it is 25 (as above).

Do you think it would be reasonable to set a support value of `100` for these cases? I understand (I think) the issue that you've brought up elsewhere in which a sequence that is not identical to an identical pair may nevertheless be identical when just a subset of its sites are selected in a bootstrap round, in which case the support value for the actually-identical pair can decrease. Looking at the support values on the edges in a clade of identical sequences (when `-keep-ident` is used), they are quite variable (for the above reason, I assume), and to a naive observer (like me) are potentially misleading because the variable support would naturally be interpreted as being due to variation in the sequences. Simply putting `100` on all those edges could be argued for, I think.

Or maybe this behavior could just be documented and an option added to specify a constant support value to be added to all internal nodes created in this final addition of identical samples.

I can easily deal with this _post hoc_ now that it's clear what's going on, so there's no urgency (for me) on changing anything. Thanks for your help. Let me know if I can help (I barely know C++, but I can write documentation :-)).

**Comment by heikotree** [comment] 2024-11-03 13:38
Dear Terry, 

The way you describe and tested it, the branch support can clearly not be set to 100%.

Since -keep-ident changed the fact that there were branches with no support values, proves that this was caused by identical sequences.


What IQ-TREE does is that if there is a set of identical sequences, it removes them all but two before running the tree search. 
Why all but two? Because with two IQ-TREE is able to compute a support value for the inner branch to them. 
One might think, that identical sequences should be in a subtree with 100% support.
However, if the next-closest sequences are only differing by wildcard characters (e.g. N, Y, R, W, S, M, K, etc in DNA), gaps or singleton mutations, they would fit just es well between the identical sequences leading to lower support of the above mentioned branch.

What happens to the removed braches? Since they are identical with the two remaining sequences (from the identical group) they would end up together with them if kept in the analysis (as enforced with the -keep-ident flag), they are (re)inserted randomly into the branches to their identical with zero branch lengths. As these sequences are identical they do not carry any information that could support any branching order of the identical. Thus, the branch support cannot be set to 100. 

For example if you have 4 identical sequences in a dataset that are clearly distinct from the other sequences in the dataset, then you have 15 possibilities how to re-insert the 2 deleted sequences and all of those should be equally likely - thus, each one of these subtrees cannot have branch supports of 100.


In the Figure caption of the trees you could state something like “Branches without support values mark subtrees of identical sequences, here no signal exists to support any of the possible groupings of the identical sequences.” 

I hope this explanations help to unterstand the scenario.

Best wishes, 
Heiko


> On 03.11.2024, at 11:23, Terry Jones ***@***.***> wrote:
> 
> 
> Hi @roblanf - thanks for the reply. You're right, the issue goes away when I add -keep-ident. I also checked the count of 'is ignored but added at the end' messages in the log of my original run, and it is 25 (as above).
> Do you think it would be reasonable to set a support value of 100 for these cases? I understand (I think) the issue that you've brought up elsewhere in which a sequence that is not identical to an identical pair may nevertheless be identical when just a subset of its sites are selected in a bootstrap round, in which case the support value for the actually-identical pair can decrease. Looking at the support values on the edges in a clade of identical sequences (when -keep-ident is used), they are quite variable (for the above reason, I assume), and to a naive observer (like me) are potentially misleading because the variable support would naturally be interpreted as being due to variation in the sequences. Simply putting 100 on all those edges could be argued for, I think.
> Or maybe this behavior could just be documented and an option added to specify a constant support value to be added to all internal nodes created in this final addition of identical samples.
> I can easily deal with this post hoc now that it's clear what's going on, so there's no urgency (for me) on changing anything. Thanks for your help. Let me know if I can help (I barely know C++, but I can write documentation :-)).
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-----------------------------------------------------------------------------
Heiko Schmidt
Center for Integrative Bioinformatics Vienna (CIBIV) 
Structural and Computational Biology 
University of Vienna / Max Perutz Labs
http://www.cibiv.at/
-----------------------------------------------------------------------------

**Comment by terrycojones** [comment] 2024-11-03 16:37
Hi Heiko

Thanks for the explanation - I see that the suggestion of adding 100 support to all edges is really wrong. I do have a few questions, if you still have time to reply.

* You say "Why all but two? Because with two IQ-TREE is able to compute a support value for the inner branch to them." In my ASCII art picture, that would be the edge from `A` to `B`, right? But there is no support label on `B`. So it seems that if a support value has been computed for these two identical sequences, it hasn't been put on the edge leading to them. Maybe the reason is that (as in my case) if there are more that two identical sequences, it is not clear what the support value should be, since it is not for sure that all the identical sequences will always (and only) group under B. So maybe the support label is only added to `B` if there are exactly two identical sequences?
* If there are identical sequences, are the two that are in the analysis guaranteed to end up as immediate siblings to each other in the final tree, or is this just highly likely? I understand that the support value leading to them (if they are siblings) will depend on whether other similar-but-not-identical sequences exist (and sequence length and number of differences, etc). I'm just wondering if there is any absolute guarantee the identical ones will be together?

Thanks again!

**Comment by roblanf** [comment] 2024-11-07 00:33
to the second of your questions - there is no guarantee that identical sequences will end up together. 

Here's an extreme case which might help to illustrate the point (and the more general point that there are no shortcuts to bootstrap values in this case). 

Imagine you have 1000 sequences, 2 of which are identical. It's always possible (more or less likely, depending on the alignment) that in a bootstrap resampled alignment those 2 identical sequences are joined by many other identical sequences. For example, imagine that most of the alignment is constant sites, and that in a particular bootstrap sample we have ONLY sampled constant sites. The resulting tree should be completely random, and making it unlikely that the two genuinely identical seuqences would be placed together.

So, we can never have an expectation that identical sequences will go together with 100% bootstrap support. 

This gets to what bootstraps are actually measuring - they are measuring the sampling variance of a split. As long as the sampling variance is >0 (which for all practical datasets, it is), the bootstraps _can_ be <100%, no matter if the sequences are identical. 

Hopefullly that helps!

I'll close this issue off, but feel free to continue the discussion, 
Rob

**Closed by roblanf** 2024-11-07 00:33 UTC

**Comment by terrycojones** [comment] 2024-11-07 21:54
Hi Rob

I wasn't referring to where the pair of identical sequences end up in a particular bootstrap run, but rather where they are in the underlying tree that the overall bootstrap support values are added to. I was imagining that it might be that in building the best tree it can, there might be some guarantee that the two identical sequences would end up as immediate siblings of the same internal node. That's before any bootstrapping occurs. Later, the bootstrap happens and a support value is added to the node that is the parent of both, and this might be <100, and other identical sequences and then added below that node.  If there were no such guarantee, then when the identical sequences are added, they might be added as descendants of two tips that are not siblings even though they are identical. (In my description, I am assuming that iqtree2 is adding support to the best tree it finds initially, rather than calculating an MCC tree from running a bunch of bootstraps.)

Another question/suggestion: iqtree2 must choose some internal node to use for the trifurcation for the unrooted Newick. There doesn't seem to be an option to be able to specify that the internal node on the edge leading to a particular tip be used for the trifurcation node that starts the Newick string. If this were possible, later rerooting the tree on that edge would be trivial and would not require that support values be moved around because they would all have been computed in a way that would be compatible with the newly-rooted topology.  Am I making sense? I can draw a picture if not :-)

Thanks for the reply!

**Comment by roblanf** [comment] 2024-11-11 02:38
@terrycojones I didn't completely understand your first paragraph, but you're right that IQ-TREE estimates a single ML tree first and adds support to that tree.

Not sure about your second point, but does the `-o` option to specify an outgroup help you?

**Comment by terrycojones** [comment] 2024-11-15 11:48
Hi @roblanf Thanks for another reply. The `-o` option is some help. I'm trying to get a rooted tree and was having trouble rooting on a edge that is distant from the arbitrary trifurcation point of an unrooted tree (see https://github.com/jeetsukumaran/DendroPy/issues/216 if you're curious). In the end I swapped dendropy's rooting for that of ete3 and my issue goes away. Dendropy doesn't move node labels (which is correct if they are just node names) whereas ete3 does (which is correct if the node labels are actually support values - in which case the labels beween the trifurcation node and the new root have to be shifted). It would be good if dendropy and ete3 allowed you to specify whether node labels are support values or not, but neither package does (yet).

Thanks again!
